[project]
name = "ml-research-12weeks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "absl-py==2.3.1",
    "aiofiles==24.1.0",
    "aiohappyeyeballs==2.6.1",
    "aiohttp==3.13.3",
    "aiosignal==1.4.0",
    "albucore==0.0.24",
    "albumentations==2.0.8",
    "altair==6.0.0",
    "annotated-doc==0.0.4",
    "annotated-types==0.7.0",
    "anyio==4.12.1",
    "argon2-cffi==25.1.0",
    "argon2-cffi-bindings==25.1.0",
    "arrow==1.4.0",
    "asttokens==3.0.1",
    "async-lru==2.1.0",
    "attrs==25.4.0",
    "babel==2.17.0",
    "beautifulsoup4==4.14.3",
    "black==26.1.0",
    "bleach==6.3.0",
    "blinker==1.9.0",
    "brotli==1.2.0",
    "cachetools==6.2.6",
    "captum==0.8.0",
    "certifi==2026.1.4",
    "cffi==2.0.0",
    "charset-normalizer==3.4.4",
    "click==8.3.1",
    "cmdstanpy==1.3.0",
    "colorama==0.4.6",
    "comm==0.2.3",
    "contourpy==1.3.3",
    "cycler==0.12.1",
    "debugpy==1.8.19",
    "decorator==5.2.1",
    "defusedxml==0.7.1",
    "executing==2.2.1",
    "fastapi==0.128.0",
    "fastjsonschema==2.21.2",
    "ffmpy==1.0.0",
    "filelock==3.20.0",
    "fonttools==4.61.1",
    "fqdn==1.5.1",
    "frozenlist==1.8.0",
    "fsspec==2025.12.0",
    "gitdb==4.0.12",
    "gitpython==3.1.46",
    "gradio==6.4.0",
    "gradio-client==2.0.3",
    "groovy==0.1.2",
    "grpcio==1.76.0",
    "h11==0.16.0",
    "hf-xet==1.2.0",
    "holidays==0.89",
    "httpcore==1.0.9",
    "httpx==0.28.1",
    "huggingface-hub==1.3.4",
    "idna==3.11",
    "importlib-resources==6.5.2",
    "iniconfig==2.3.0",
    "ipykernel==7.1.0",
    "ipython==9.9.0",
    "ipython-pygments-lexers==1.1.1",
    "isoduration==20.11.0",
    "jedi==0.19.2",
    "jinja2==3.1.6",
    "joblib==1.5.3",
    "json5==0.13.0",
    "jsonpointer==3.0.0",
    "jsonschema==4.26.0",
    "jsonschema-specifications==2025.9.1",
    "jupyter-client==8.8.0",
    "jupyter-core==5.9.1",
    "jupyter-events==0.12.0",
    "jupyter-lsp==2.3.0",
    "jupyter-server==2.17.0",
    "jupyter-server-terminals==0.5.4",
    "jupyterlab==4.5.3",
    "jupyterlab-pygments==0.3.0",
    "jupyterlab-server==2.28.0",
    "kiwisolver==1.4.9",
    "lark==1.3.1",
    "lightning-utilities==0.15.2",
    "markdown==3.10.1",
    "markdown-it-py==4.0.0",
    "markupsafe==2.1.5",
    "matplotlib==3.10.8",
    "matplotlib-inline==0.2.1",
    "mdurl==0.1.2",
    "mistune==3.2.0",
    "mpmath==1.3.0",
    "multidict==6.7.1",
    "mypy-extensions==1.1.0",
    "narwhals==2.15.0",
    "nbclient==0.10.4",
    "nbconvert==7.16.6",
    "nbformat==5.10.4",
    "nest-asyncio==1.6.0",
    "networkx==3.6.1",
    "neuralprophet==0.8.0",
    "notebook-shim==0.2.4",
    "numpy==1.26.4",
    "opencv-python==4.10.0.84",
    "opencv-python-headless==4.10.0.84",
    "orjson==3.11.5",
    "packaging==26.0",
    "pandas==2.3.3",
    "pandocfilters==1.5.1",
    "parso==0.8.5",
    "pathspec==1.0.4",
    "patsy==1.0.2",
    "pillow==12.0.0",
    "platformdirs==4.5.1",
    "plotly==5.24.1",
    "pluggy==1.6.0",
    "polars==1.37.1",
    "polars-runtime-32==1.37.1",
    "prometheus-client==0.24.1",
    "prompt-toolkit==3.0.52",
    "propcache==0.4.1",
    "prophet==1.3.0",
    "protobuf==6.33.4",
    "psutil==7.2.1",
    "pure-eval==0.2.3",
    "pyarrow==23.0.0",
    "pycparser==3.0",
    "pydantic==2.12.5",
    "pydantic-core==2.41.5",
    "pydeck==0.9.1",
    "pydub==0.25.1",
    "pygments==2.19.2",
    "pyparsing==3.3.2",
    "pytest==9.0.2",
    "python-dateutil==2.9.0.post0",
    "python-json-logger==4.0.0",
    "python-multipart==0.0.22",
    "pytokens==0.4.0",
    "pytorch-lightning==1.9.5",
    "pytz==2025.2",
    "pywinpty==3.0.2",
    "pyyaml==6.0.3",
    "pyzmq==27.1.0",
    "referencing==0.37.0",
    "requests==2.32.5",
    "rfc3339-validator==0.1.4",
    "rfc3986-validator==0.1.1",
    "rfc3987-syntax==1.1.0",
    "rich==14.3.1",
    "rpds-py==0.30.0",
    "safehttpx==0.1.7",
    "safetensors==0.7.0",
    "scikit-learn==1.8.0",
    "scipy==1.17.0",
    "seaborn==0.13.2",
    "semantic-version==2.10.0",
    "send2trash==2.1.0",
    "sentry-sdk==2.50.0",
    "setuptools==70.2.0",
    "shellingham==1.5.4",
    "simsimd==6.5.12",
    "six==1.17.0",
    "smmap==5.0.2",
    "soupsieve==2.8.3",
    "stack-data==0.6.3",
    "stanio==0.5.1",
    "starlette==0.50.0",
    "statsmodels==0.14.6",
    "streamlit==1.53.1",
    "stringzilla==4.6.0",
    "sympy==1.14.0",
    "tenacity==9.1.2",
    "tensorboard==2.20.0",
    "tensorboard-data-server==0.7.2",
    "terminado==0.18.1",
    "threadpoolctl==3.6.0",
    "timm==1.0.24",
    "tinycss2==1.4.0",
    "toml==0.10.2",
    "tomlkit==0.13.3",
    "torch==2.7.1",
    "torchaudio==2.7.1",
    "torchmetrics==1.8.2",
    "torchvision==0.22.1",
    "tornado==6.5.4",
    "tqdm==4.67.1",
    "traitlets==5.14.3",
    "typer==0.21.1",
    "typer-slim==0.21.1",
    "typing-extensions==4.15.0",
    "typing-inspection==0.4.2",
    "tzdata==2025.3",
    "ultralytics==8.4.8",
    "ultralytics-thop==2.0.18",
    "uri-template==1.3.0",
    "urllib3==2.6.3",
    "uvicorn==0.40.0",
    "wandb==0.24.0",
    "watchdog==6.0.0",
    "wcwidth==0.5.0",
    "webcolors==25.10.0",
    "webencodings==0.5.1",
    "websocket-client==1.9.0",
    "werkzeug==3.1.5",
    "yarl==1.22.0",
]
